BasicMachineLearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="welcome"),
    path("", include('core.urls')),
    path("posts/", include('posts.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('homepage/', views.homepage, name='homepage'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('new_post/', views.NewPost, name='newpost'),
    path('<int:pk>/', views.PostDetail, name='postdetail'),
    path('<int:pk>/delete/', views.DeletePost, name='deletepost'),
    path('<int:pk>/edit/', views.EditPost, name='editpost'),
]

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    can_create_post = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Username',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

class SingupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Username',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder': 'Email Address',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirm Password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import SingupForm
from posts.models import Category, Post

def index(request):
    return render(request, 'core/welcome.html')

@login_required
def homepage(request):
    query = request.GET.get('query', '')
    posts = Post.objects.all()
    categories = Category.objects.all()
    if query:
        posts = posts.filter(title__icontains=query)

    return render(request, 'core/homepage.html', {
        'posts': posts,
        'query': query,
        'categories': categories
    })

def signup(request):
    if request.method == 'POST':
        form = SingupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SingupForm

    return render(request, 'core/signup.html', {'form': form})

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %} | BML</title>

        <!-- Meta Tags -->
        <meta charset="utf-8">
        <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Style Sheet -->
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/base.css' %}">
        {% block webstyle %}{% endblock %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>

    <body>
        <!-- Navigator Bar -->
        <nav>
            <a href="{% url 'core:homepage' %}" class="nav-logo">BasicMachineLearning (BML)</a>

            <div class="user-info">
                {% if user.is_authenticated %}
                    <span class="greeting">Hi, {{ user.username }}!</span>
                    {% block NavBarContent %}{% endblock %}
                    <form action="{% url 'core:logout' %}" method="post" class="logout-form">
                        {% csrf_token %}
                        <button type="submit" class="nav-signout">Log Out</button>
                    </form>
                {% endif %}
            </div>
        </nav>

        <!-- Contents -->
        {% block content %}{% endblock %}

        <!-- Footer -->
        <footer id="footer">
            <div class="inner">
                <div class="footer-info">
                    <p>DrunK Donkey Kong Studios &bull; 
                        <span>Salt Lake City, UT &bull; Main (801) 558 - 6005</span>
                    </p>
                </div>
                
                <div. class="social-icons">
                    <a href="https://github.com/DKunLee" target="blank"><i class="fa-brands fa-github"></i></a>
                    <a href="https://www.linkedin.com/in/dongkun-lee-4607a2228" target="blank"><i class="fa-brands fa-linkedin"></i></a>
                    <a href="mailto:ldkun2001@gmail.com" target="blank"><i class="fa-brands fa-google"></i></a>
                </div>
            </div>
        </footer>
    </body>
</html>

core/templates/core/homepage.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Homepage{% endblock %}

{% block webstyle %}
    <!-- Style Sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/homepage.css' %}">
{% endblock %}

{% block NavBarContent %}
    <!-- Navigator Bar Contents -->
    {% if user.is_authenticated and user.profile.can_create_post %}
        <form action="{% url 'posts:newpost' %}" class="createpost-form">
            <button type="submit" class="nav-createpost">Create</button>
        </form>
    {% endif %}
{% endblock %}

{% block content %}
    <!-- Contents -->
    <section id="front">
        <div class="inner">
            <header>
                <h1>Welcome to BML</h1>
                <h3>Basic Machine Learning</h3>
                <p>
                    Basic knowledges of machine learning with visualization<br>
                    designed by <a href="https://www.linkedin.com/in/dongkun-lee-4607a2228" target="blank">DK (Dongkun) Lee</a>
                </p>
            </header>
        </div>
    </section>

    <h1 class="PostText">Posts</h1>

    <form method="get" action="{% url 'core:homepage' %}" class="search-bar">
        <input name="query" type="text" value="{{ query }}" pattern=".*\S.*" required>
        <button class="search-btn" type="submit">
            <span>Search</span>
        </button>
    </form>
    

    <div class="post-grid">
        {% for post in posts %}
            <div class="post-item">
                <a href="{% url 'posts:postdetail' post.id %}">
                    <div class="thumbnail-frame">
                        <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}">
                    </div>
                    <h2>{{ post.title }}</h2>
                </a>
                <p>{{ post.description }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/onlyfooter.html' %}
{% load static %}

{% block title %}Log in{% endblock %}

{% block webstyle %}
    <!-- Style Sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/account_format.css' %}">
{% endblock %}

{% block content %}
    <!-- Logging In Contents -->
    <div class="account-container" id="login-container">
        <h1 class="signup-title">Log in</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="form-group">
                <label class="form-label">Username</label><br>
                {{ form.username }}
            </div>

            <div class="form-group">
                <label class="form-label">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="error-container">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="submit-button">Log in</button>
        </form>
    </div>
{% endblock %}

core/templates/core/onlyfooter.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %} | BML</title>

        <!-- Meta Tags -->
        <meta charset="utf-8">
        <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block webstyle %}{% endblock %}

        <!-- Style Sheet -->
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/footer.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>

    <body>
        <!-- Contents -->
        {% block content %}{% endblock %}
        
        <!-- Footer -->
        <footer id="footer">
            <div class="inner">
                <div class="footer-info">
                    <p>DrunK Donkey Kong Studios &bull; 
                        <span>Salt Lake City, UT &bull; Main (801) 558 - 6005</span>
                    </p>
                </div>
                
                <div. class="social-icons">
                    <a href="https://github.com/DKunLee" target="blank"><i class="fa-brands fa-github"></i></a>
                    <a href="https://www.linkedin.com/in/dongkun-lee-4607a2228" target="blank"><i class="fa-brands fa-linkedin"></i></a>
                    <a href="mailto:ldkun2001@gmail.com" target="blank"><i class="fa-brands fa-google"></i></a>
                </div>
            </div>
        </footer>
    </body>
</html>

core/templates/core/signup.html
{% extends 'core/onlyfooter.html' %}
{% load static %}

{% block title %}Sign up{% endblock %}

{% block webstyle %}
    <!-- Style Sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/account_format.css' %}">
{% endblock %}

{% block content %}
    <!-- Account Making Contents -->
    <div class="account-container">
        <h1 class="account-title">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label">Username</label><br>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label class="form-label">Email</label><br>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label class="form-label">Password</label><br>
                {{ form.password1 }}
            </div>
            <div class="form-group">
                <label class="form-label">Repeat Password</label><br>
                {{ form.password2 }}
            </div>

            
            {% if form.errors or form.non_field_errors %}
                <div class="error-container">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="submit-button">Sign up</button>
        </form>
    </div>
{% endblock %}

core/templates/core/welcome.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Welcome | BML</title>

        <!-- Meta Tags -->
        <meta charset="utf-8">
        <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Style Sheets -->      
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/welcome.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>

    <body class="welcome-page">
        <!-- Welcome -->
        <section id="welcome">
            <div class="inner">
                <header>
                    <h1>Welcome to BML</h1>
                    <h3>Basic Machine Learning</h3>
                    <p>
                        Basic knowledges of machine learning with visualization<br>
                        designed by <a href="https://www.linkedin.com/in/dongkun-lee-4607a2228" target="blank">DK (Dongkun) Lee</a>
                    </p>
                </header>
                <h4>Sign up to get started</h4>
                <a href="#account" class="ScrlDownToButtons">Down to SignUp button</a>
            </div>
        </section>
    
        <!-- Account -->
        <div id="account">
            <div class="inner">
                <a href="{% url 'core:signup' %}" class="SignUp">Sign Up</a>
                <a href="{% url 'core:login' %}" class="LogIn">Log In</a>
            </div>
        </div>

        <!-- Footer -->
        <footer id="footer">
            <div class="inner">
                <div class="footer-info">
                    <p>DrunK Donkey Kong Studios &bull; 
                        <span>Salt Lake City, UT &bull; Main (801) 558 - 6005</span>
                    </p>
                </div>
                
                <div. class="social-icons">
                    <a href="https://github.com/DKunLee" target="blank"><i class="fa-brands fa-github"></i></a>
                    <a href="https://www.linkedin.com/in/dongkun-lee-4607a2228" target="blank"><i class="fa-brands fa-linkedin"></i></a>
                    <a href="mailto:ldkun2001@gmail.com" target="blank"><i class="fa-brands fa-google"></i></a>
                </div>
            </div>
        </footer>
    </body>
</html>