BasicMachineLearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="welcome"),
    path("", include('core.urls')),
    path("posts/", include('posts.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('homepage/', views.homepage, name='homepage'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('new_post/', views.NewPost, name='newpost'),
    path('<int:pk>/', views.PostDetail, name='postdetail'),
    path('<int:pk>/delete/', views.DeletePost, name='deletepost'),
    path('<int:pk>/edit/', views.EditPost, name='editpost'),
]

posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


class Category(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Post(models.Model):
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField()
    content = CKEditor5Field('Text', config_name='extends')
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to='/media/post')
    publish_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('publish_date',)
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from .models import Post
from django_ckeditor_5.widgets import CKEditor5Widget
from .models import Category

class NewPostForm(forms.ModelForm):
    thumbnail = forms.ImageField(required=True)

    def __init__(self, *args, **kwargs):
        super(NewPostForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = True
        self.fields['category'].queryset = Category.objects.all()
        self.fields['category'].widget.attrs.update({
            'class': 'form-control',
        })

    class Meta:
        model = Post
        fields = ['title', 'description', 'content', 'category', 'thumbnail']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Title'
                },
            ),
            'description': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Short summary of the post'
                },
            ),
            'content': CKEditor5Widget(
                attrs={
                    'class': 'django_ckeditor_5'
                },
                config_name='extends',
            ),
        }
    

class EditPostForm(forms.ModelForm):
    thumbnail = forms.ImageField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].required = True
        self.fields['category'].queryset = Category.objects.all()
        self.fields['category'].widget.attrs.update({
            'class': 'form-control',
        })

    class Meta:
        model = Post
        fields = ['title', 'description', 'content', 'category', 'thumbnail']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Title'
                },
            ),
            'description': forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Short summary of the post'
                },
            ),
            'content': CKEditor5Widget(
                attrs={
                    'class': 'django_ckeditor_5'
                },
                config_name='extends',
            ),
        }

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import redirect

from .forms import NewPostForm, EditPostForm
from .models import Post

def PostDetail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'posts/post.html', {'post': post})

@login_required
def NewPost(request):
    if request.method == "POST":
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Your post has been added')
            return redirect('posts:postdetail', pk=post.pk)
        else:
            messages.warning(request, f'There are errors in form. \n{form.errors}')
    else:
        form = NewPostForm()
        
    return render(request, 'posts/createpost.html', {'form': form})

@login_required
def DeletePost(request, pk):
    post = get_object_or_404(Post, pk=pk, author=request.user)
    post.delete()

    return redirect('core:homepage')


@login_required
def EditPost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = EditPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your post has been added')
            return redirect('posts:postdetail', pk=post.pk)
        else:
            messages.warning(request, f'There are errors in form. \n{form.errors}')
    else:
        form = EditPostForm(instance=post)
        
    return render(request, 'posts/editpost.html', {'form': form, 'post': post})

posts/templates/posts/createpost.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Create Post{% endblock %}

{% block webstyle %}
    <!-- Style Sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/homepage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/createpostpage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/ckeditor_custom.css' %}">
    <script src="{% static 'django_ckeditor_5/dist/bundle.js' %}"></script>
    <link rel="stylesheet" href="{% static 'django_ckeditor_5/css/styles.css' %}">  
{% endblock %}

{% block content %}
    <!-- Creating Post Contents -->
    <div class="container">
        <hr>
            <p class="fs-1 text-center"><strong class="text-secondary">Add Post</strong></p>
        <hr>
        <form id="createpost-form" method="post" action="{% url 'posts:newpost' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button type="submit" class="btn-submit">Submit</button>
        </form>
    </div>

    <script>
        document.querySelector('#createpost-form').addEventListener('submit', function() {
            document.querySelector('#createpost-form button[type="submit"]').disabled = true;
        });
    </script>
{% endblock %}

posts/templates/posts/editpost.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Edit Post{% endblock %}

{% block webstyle %}
    <!-- Style Sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/homepage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/createpostpage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/ckeditor_custom.css' %}">
    <script src="{% static 'django_ckeditor_5/dist/bundle.js' %}"></script>
    <link rel="stylesheet" href="{% static 'django_ckeditor_5/css/styles.css' %}">
{% endblock %}

{% block content %}
    <!-- Editing Post Contents -->
    <div class="container">
        <hr>
            <p class="fs-1 text-center"><strong class="text-secondary">Edit Post</strong></p>
        <hr>
        <form id="editpost-form" method="post" action="{% url 'posts:editpost' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button type="submit" class="btn-submit">Submit</button>
        </form>
    </div>

    <script>
        document.querySelector('#editpost-form').addEventListener('submit', function() {
            document.querySelector('#editpost-form button[type="submit"]').disabled = true;
        });
    </script>
{% endblock %}

posts/templates/posts/post.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block webstyle %}
    <!-- Style Sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/homepage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/postdetail.css' %}">
{% endblock %}

{% block NavBarContent %}
    <!-- Navigator Bar -->
    {% if request.user == post.author %}
        <div class="onlyuser">
            <a href="{% url 'posts:editpost' post.id %}" class="edit-form">
                <button type="submit" class="nav-edit">Edit</button>
            </a>
            <a href="{% url 'posts:deletepost' post.id %}" class="delete-form">
                <button type="submit" class="nav-delete">Delete</button>
            </a>
        </div>
    {% endif %}
{% endblock %}

{% block content %}
    <!-- Displaying Post -->
    <div class="post-container">
        <div class="post-header">
            <h1 class="post-title">{{ post.title }}</h1>
            <div class="post-meta">
                <span class="post-author">By {{ post.author }}</span>
                <span class="post-date">{{ post.publish_date }}</span>
            </div>
        </div>
        <div class="post-body">
            <p>{{ post.content|safe }}</p>
        </div>
    </div>
{% endblock %}